"""covid item

Revision ID: ad08a8379c12
Revises: 3c403aee5d08
Create Date: 2020-05-10 17:03:25.247929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad08a8379c12'
down_revision = '3c403aee5d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('covid_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Integer(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('recovered', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('total_confirmed', sa.Integer(), nullable=False),
    sa.Column('total_active', sa.Integer(), nullable=False),
    sa.Column('total_recovered', sa.Integer(), nullable=False),
    sa.Column('total_deaths', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('covid_items')
    # ### end Alembic commands ###
